version: '3'
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - ".env"
    command: [
      '--wait_timeout=360000',
      '--log-bin=bin.log',
      '--log-bin-index=bin-log.index',
      '--max_binlog_size=100M',
      '--binlog-format=MIXED',
      '--slow-query-log',
      '--general_log=1',
      '--expire_logs_days=10',
      '--sync_binlog=1'
    ]
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_USER=${MARIADB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./server/inc/databases:/var/lib/mysql
      - ./server/inc/innodb.cnf:/etc/mysql/conf.d/innodb.cnf:ro

networks:
  default:
    external:
      name: database
